language: c

sudo: false # only for faster builds

os:
  - windows
  - linux

compiler:
  - gcc

script:
  - gcc -coverage -O0 ./Timer.c -o Timer
  - ./Timer
  - gcov Timer.c

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  file: "Timer.exe"
  skip_cleanup: true
  on:
    tags: true
