name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: windows-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting your first issue! Please include all the pertaining logs you can so I can try and help narrow down the issue. I am pretty busy but I will reply as soon as I can! (RawTechnique)'' first issue'
        pr-message: 'Thanks for making your first pull-request! I am pretty busy but I will reply as soon as I can! (RawTechnique)'' first pr'
