name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: windows-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Your issue submission has been archived (marked as stale) due to inactivity'
        stale-pr-message: 'Your pull-request has been archived (marked as stale) due to inactivity'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
